import { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Script from 'next/script';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Pype AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
        <Script
          id="theme-toggle-script"
          strategy="afterInteractive"
        >
          
          {`
            document.addEventListener('DOMContentLoaded', () => {
              const toggleButton = document.querySelector('.theme-toggle-btn');
              const storedTheme = localStorage.getItem('theme');
              if (storedTheme === 'dark') {
                document.body.classList.add('dark-mode');
              } else {
                document.body.classList.remove('dark-mode');
              }
              if (toggleButton) {
                toggleButton.addEventListener('click', () => {
                  const isDarkMode = document.body.classList.toggle('dark-mode');
                  localStorage.setItem('theme', isDarkMode ? 'dark' : 'light');
                });
              }
            });
          `}
        </Script>
      </body>
    </html>
  );
}
